# Section 1 Homework

## Q1

In [12]:
import numpy as np
import pandas as pd

pd.__version__

'3.0.6'

## Q2

In [13]:
data = pd.read_csv('../car_fuel_efficiency_2026.csv')

In [14]:
df = pd.DataFrame(data)
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,9123.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.45,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,22.84,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,239.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,254.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,270.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

Answer = 10000

## Q3

In [15]:
df['fuel_type'].nunique()

3

Answer = 3

## Q4

In [16]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Answer: 2

## Q5

In [17]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

Answer: 41.2

## Q6

In [18]:
median_hp = df['horsepower'].median()
print(f"Median horsepower is {median_hp}")
count_null_hp = df.horsepower.isnull().sum()
print(f"Number of null horsepower entries: {count_null_hp}")

Median horsepower is 254.0
Number of null horsepower entries: 877

In [19]:
df['horsepower'] = df['horsepower'].fillna(value = median_hp)
new_median_hp = df['horsepower'].median()
print(f"New median horsepower is {new_median_hp}")

New median horsepower is 254.0

Answer: No

## Q7

In [94]:
asian_cars = df[
    df['origin'] == 'Asia'
]
X = asian_cars[['vehicle_weight', 'model_year']].head(7)
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [95]:
XTX = X.T.dot(X)
XTX

                vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424

In [96]:
XTX_inverse = np.linalg.pinv(XTX)
XTX_inverse

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [97]:
X_transpose = X.T
XTXiXT = XTX_inverse.dot(X_transpose)
XTXiXT

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [98]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape

(7,)

In [101]:
w = XTXiXT.dot(y)
w

array([0.13644777, 0.2327492 ])

In [102]:
w.sum()

np.float64(0.3691969690492901)

Answer: 0.369